fixes the breaking change introduced by 0.30.0
```
Error: abstract `def Enumerable(T)#each(&block)` must be implemented by Callback::ResultSet(T)
```

this fixes a transient dependency of optarg which is not compatible with
0.30.0.
we use the fork until https://github.com/mosop/callback/pull/3 has been
merged and optarg has been updated to that version.